= Install by using the Knative Operator

Knative offers a https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[Kubernetes Operator] that enables the installation, configuration, and management of Knative components. The Serving and Eventing components can be installed separately or together on the Kubernetes cluster.

== Knative Installation Prerequisites

Installation of Knative requires the following prerequisites to be satisfied:

* Knative seamlessly supports the majority of local Kubernetes deployments. Consider using a local, single-node cluster with at least 3 CPUs and 4 GB of memory. 
* For a single-node cluster, ensure a minimum configuration of 6 CPUs, 6 GB of memory, as well as 30 GB of disk storage.
* For multi-node clusters, each node should be provisioned with at least 2 CPUs, 4 GB of memory, and 20 GB of disk storage.
* A Kubernetes cluster running version v1.26 or a more.
* `kubectl` CLI should be installed.

== Install the Knative Operator

First, we need to install the Knative operator. Execute the following command to install the latest stable Operator release: 
[source,bash]
kubectl apply -f https://github.com/knative/operator/releases/download/knative-{knative-release}/operator.yaml

Expected output:
[source,bash]
secret/operator-webhook-certs unchanged
deployment.apps/operator-webhook configured
service/operator-webhook unchanged
customresourcedefinition.apiextensions.k8s.io/knativeeventings.operator.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/knativeservings.operator.knative.dev unchanged
clusterrole.rbac.authorization.k8s.io/knative-serving-operator-aggregated configured
clusterrole.rbac.authorization.k8s.io/knative-serving-operator-aggregated-stable configured
clusterrole.rbac.authorization.k8s.io/knative-eventing-operator-aggregated configured
clusterrole.rbac.authorization.k8s.io/knative-eventing-operator-aggregated-stable configured
clusterrole.rbac.authorization.k8s.io/knative-serving-operator unchanged
clusterrole.rbac.authorization.k8s.io/knative-eventing-operator unchanged
serviceaccount/knative-operator unchanged
clusterrolebinding.rbac.authorization.k8s.io/knative-serving-operator unchanged
clusterrolebinding.rbac.authorization.k8s.io/knative-eventing-operator unchanged
role.rbac.authorization.k8s.io/knative-operator-webhook unchanged
clusterrole.rbac.authorization.k8s.io/knative-operator-webhook unchanged
serviceaccount/operator-webhook unchanged
rolebinding.rbac.authorization.k8s.io/operator-webhook unchanged
clusterrolebinding.rbac.authorization.k8s.io/operator-webhook unchanged
clusterrolebinding.rbac.authorization.k8s.io/knative-serving-operator-aggregated unchanged
clusterrolebinding.rbac.authorization.k8s.io/knative-serving-operator-aggregated-stable unchanged
clusterrolebinding.rbac.authorization.k8s.io/knative-eventing-operator-aggregated unchanged
clusterrolebinding.rbac.authorization.k8s.io/knative-eventing-operator-aggregated-stable unchanged
configmap/config-logging unchanged
configmap/config-observability unchanged
deployment.apps/knative-operator configured



Switch the existing namespace to default:
[source,bash]
kubectl config set-context --current --namespace=default


. Confirm successful installation of the Knative operator:
[source,bash]
kubectl get deployment knative-operator

Expected output: 
[source,bash]
  NAME               READY   UP-TO-DATE   AVAILABLE   AGE
  knative-operator   1/1     1            1           35h


== Knative Serving Installation

Knative Serving installation needs the following steps:

=== Create the custom resource for Knative Serving
. Create a file `knative-serving.yaml` with the following content:
[source,yaml]
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving

+
[NOTE] 
====
In the absence of a set version using spec.version, the Operator automatically defaults to the latest available version.
====
+ 


. Create the custom resource by applying the `knative-serving.yaml` file:
[source,bash]
kubectl apply -f knative-serving.yaml

Expected output:
[source,bash]
namespace/knative-serving configured
knativeserving.operator.knative.dev/knative-serving configured


=== Installation of the networking layer

The Knative Operator allows configuring the Knative Serving component with various network layer alternatives. By default, it uses Istio  as the network layer, in the absence of specific ingress specification in the Knative Serving Custom Resource (CR). However, Istio needs to be installed in the cluster. For simpler configuration, you may find it more suitable to set up Kourier as your networking layer. 


The following steps will install Kourier and integrate it with Knative:

. Add the spec.ingress.kourier and spec.config.network configurations into the previously created knative-serving.yaml file:
[source,yaml]
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  # ...
  ingress:
    kourier:
      enabled: true
  config:
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"

. Apply the YAML file:
[source,bash]
kubectl apply -f knative-serving.yaml

. Retrieve the External IP address or Canonical Name (CNAME):
[source,bash]
kubectl --namespace knative-serving get service kourier
+
Expected output would be as follows (It can vary based on the underlying infrastructure):
[source,bash]
NAME      TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                      AGE
kourier   LoadBalancer   10.101.101.116   10.101.101.116   80:30864/TCP,443:31928/TCP   35h



=== Validate the deployment of Knative Serving

. Confirm Knative serving deployment. upon successful deployment, all deployments will be displayed to be ready:
[source,bash]
kubectl get deployment -n knative-serving

[source,bash]
NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
3scale-kourier-gateway   1/1     1            1           35h
activator                1/1     1            1           35h
autoscaler               1/1     1            1           35h
autoscaler-hpa           1/1     1            1           35h
controller               1/1     1            1           35h
net-kourier-controller   1/1     1            1           35h
webhook                  1/1     1            1           35h

. Verify the status of the Knative Serving Custom Resource:
[source,bash]
kubectl get KnativeServing knative-serving -n knative-serving
+
Expected output:
+
[source,bash]
NAME              VERSION               READY        REASON
knative-serving   {serving-release}     True    

=== Configure DNS

Knative supplies a Kubernetes Job called default-domain to configure Knative Serving to use sslip.io as the default DNS suffix. it can be executed by following step:

[source,bash]
kubectl apply -f https://github.com/knative/serving/releases/download/knative-{knative-release}/serving-default-domain.yaml


== Knative Eventing Installation

Knative Eventing installation needs deploying the KnativeEventing custom resource (CR). 

. Create a file `knative-eventing.yaml` with the following content:
[source,yaml]
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing

[NOTE] 
====
If the spec.version is not explicitly specified, the Operator will use the most recent available version as default.
====


. Apply the YAML file by running the command:
[source,bash]
kubectl apply -f knative-eventing.yaml

. Observe Knative eventing deployments. A ready status of all deployments indicates the successful deployment of Knative Eventing:
[source,bash]
kubectl get deployment -n knative-eventing

[source,bash]
NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
eventing-controller     1/1     1            1           35h
eventing-webhook        1/1     1            1           35h
imc-controller          1/1     1            1           35h
imc-dispatcher          1/1     1            1           35h
mt-broker-controller    1/1     1            1           35h
mt-broker-filter        1/1     1            1           35h
mt-broker-ingress       1/1     1            1           35h
pingsource-mt-adapter   0/0     0            0           35h


. Verify the status of the Knative Eventing Custom Resource by running the following command:
[source,bash]
kubectl get KnativeEventing knative-eventing -n knative-eventing

Expected Output:
[source,bash]
NAME               VERSION             READY   REASON
knative-eventing   {eventing-release}  True


=== References
* https://knative.dev/docs/install/[Installing Knative]

