:operator-release: 1.12.0


= Install by using the Knative Operator

The Knative project provides several options for installing the components such as YAML files, or operators.
This section covers the installation of the Knative components in Kubernetes by using the Knative Operator.

Depending on your application's workload, your system requirements might vary.
Knative requires at least 3 CPUs and 4 GB of memory for prototyping purposes.
To use Knative in a production environment, it requires at least Kubernetes v1.26, 6 CPUs, 6 GB of memory, and 30 GB of disk space.
For the installation process, ensure you have the `kubectl` CLI, and administrative access to a Kubernetes cluster.

== Install the Knative Operator

The first step is to install the Knative operator. 
You can install the operator for the release v{operator-release} by running the following command:
[source,bash,subs="attributes"]
kubectl apply -f https://github.com/knative/operator/releases/download/knative-v{operator-release}/operator.yaml


After installing the Knative operator, confirm successful installation by running the following commeand:
[source,bash]
kubectl get deployment knative-operator

Expected output: 
[source,bash]
  NAME               READY   UP-TO-DATE   AVAILABLE   AGE
  knative-operator   1/1     1            1           35h

The preceding command shows knative-operator deployment to be ready, indicating successful installation of of Knative operator.

== Knative Serving Installation
Knative Serving installation consists of the following steps:

1. Creating the Custom Resource for Knative Serving
2. Configure the networking layer for the Custom Resource
3. Validate the deployment of Knative Serving
4. Set up DNS.

=== Creating the Custom Resource for Knative Serving
Knative Serving specifies and manages the behaviour of your serverless workload on the kubernetes cluster. It can be installed as Kubernetes Custom Resource. 
Create a file having a name `knative-serving.yaml`, with the following content:
[source,yaml]
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving

Executing the following command first creates a namespace called `knative-serving` and then installs the Knative Serving Custom resource in that namespace:

[source,bash]
kubectl apply -f knative-serving.yaml


=== Configure the networking layer for the Custom Resource

The Knative Operator allows you to configure the Knative Serving component with different network layer alternatives. 
In the absence of specific ingress specification in the Knative Serving Custom Resource (CR), the default network layer is Istio.
However, Istio must be installed in the cluster. 
For simpler configuration, you can use Kourier as your networking layer. 

First, Edit the `knative-serving.yaml` file, and add the spec.ingress.kourier and spec.config.network configurations:
[source,yaml]
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  # ...
  ingress:
    kourier:
      enabled: true
  config:
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"

Then, execute the following command to apply the changes:
[source,bash]
kubectl apply -f knative-serving.yaml

Finally, retrieve the External IP address or Canonical Name (CNAME):
[source,bash]
kubectl --namespace knative-serving get service kourier

Expected output would be as follows (It can vary based on the underlying infrastructure):
[source,bash]
NAME      TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                      AGE
kourier   LoadBalancer   10.101.101.116   10.101.101.116   80:30864/TCP,443:31928/TCP   35h


=== Validate the deployment of Knative Serving
After running the pervious steps that installs the Knative Serving Custom Resource and configuring the network layer, confirm Knative serving deployment. 
Upon successful deployment, all deployments are displayed to be ready:
[source,bash]
kubectl get deployment -n knative-serving

Expected output:
[source,bash]
NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
3scale-kourier-gateway   1/1     1            1           35h
activator                1/1     1            1           35h
autoscaler               1/1     1            1           35h
autoscaler-hpa           1/1     1            1           35h
controller               1/1     1            1           35h
net-kourier-controller   1/1     1            1           35h
webhook                  1/1     1            1           35h


To verify the status of the Knative Serving Custom Resource you can use the following command:
[source,bash]
kubectl get KnativeServing knative-serving -n knative-serving

The following output shows Knative Serving Custom Resource to be ready, if the installation is successful.

[source,bash,subs="attributes"]
NAME              VERSION               READY        REASON
knative-serving   {operator-release}                True    


=== Set up DNS

Knative supplies a Kubernetes Job called default-domain to configure Knative Serving to use `sslip.io` as the default DNS suffix. This approach is not suitable for production environment and is suitable for development scenarios only. Executing the following command configures `sslip.io` to be the default DNS suffix:

[source,bash,subs="attributes"]
kubectl apply -f https://github.com/knative/serving/releases/download/knative-v{operator-release}/serving-default-domain.yaml


== Knative Eventing Installation

You need to deploy Knative Eventing Custom Resource to complete Knative Eventing installation. 

First, create a file having a name `knative-eventing.yaml`, with the following content:
[source,yaml]
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing


Executing the following command creates a namespace called `knative-eventing` and installs the Knative Serving Custom Resource in that namespace:

[source,bash]
kubectl apply -f knative-eventing.yaml

Afterwards, observe Knative eventing deployments. A ready status of all deployments indicates the successful deployment of Knative Eventing:
[source,bash]
kubectl get deployment -n knative-eventing


[source,bash]
NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
eventing-controller     1/1     1            1           35h
eventing-webhook        1/1     1            1           35h
imc-controller          1/1     1            1           35h
imc-dispatcher          1/1     1            1           35h
mt-broker-controller    1/1     1            1           35h
mt-broker-filter        1/1     1            1           35h
mt-broker-ingress       1/1     1            1           35h
pingsource-mt-adapter   0/0     0            0           35h


Finally, Verify the status of the Knative Eventing Custom Resource by running the following command:
[source,bash]
kubectl get KnativeEventing knative-eventing -n knative-eventing

The preceding output shows Knative Eventing Custom Resource to be ready, if the installation is successful.
[source,bash,subs="attributes"]
NAME               VERSION             READY   REASON
knative-eventing   {operator-release}              True


=== References
* https://knative.dev/docs/install/[Installing Knative]
